import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { unwrap } from '../web/src/saveEnvelope.js';
import {
  parseCampaign, buildCampaignParty, readBackSurvivors, longRest, hitDiceLeft, hitDiceMax,
  partyLevelOf, type CampaignState,
} from '../src/campaign/campaign.js';
import { advanceDay, buildWave, type ArenaRunState } from '../src/arena/run.js';
import { gatesFor, gateLocked } from '../src/arena/gates.js';
import { attemptFor } from '../src/arena/gambit.js';
import { lunch, night } from '../src/arena/day.js';
import { parseAdventure, serializeAdventure } from '../src/adventure/save.js';
import { currentScene, legalChoices, choose } from '../src/adventure/runtime.js';
import { moduleById } from '../src/data/modules/index.js';
import { Combat } from '../src/engine/combat.js';
import { buildMonster } from '../src/data/monsters.js';

/**
 * Saves written by the game as it shipped before the September 2026 refactors,
 * loaded into the game as it is now.
 *
 * The fixtures were GENERATED by the code at 5288a7e, not written by hand, so
 * they carry that code's real shapes: `hp` written on every resource record,
 * Aid's bonus stored the old way, an arena run whose door lock lived in
 * `attempts` and whose pre-fight check was keyed on the calendar day. A player
 * on that build had exactly these in localStorage.
 *
 * NEVER regenerate these. When a save format changes, add a NEW dated fixture
 * from the old code beside them; the point is that every format ever shipped
 * keeps loading.
 */
const fixture = (name: string): string =>
  readFileSync(new URL(`./fixtures/saves/${name}`, import.meta.url), 'utf8');
const unwrapped = (name: string): string => {
  const u = unwrap(fixture(name));
  if (u.kind !== 'ok') throw new Error(`${name} did not unwrap: ${u.kind}`);
  return u.raw;
};

describe('a campaign saved by the old build', () => {
  const load = (): CampaignState => {
    const c = parseCampaign(unwrapped('campaign-2026-09.json'));
    expect(c, 'the save no longer parses').toBeDefined();
    return c!;
  };

  it('builds a party with sane hit points, Aid and all', () => {
    const c = load();
    for (const hero of buildCampaignParty(c)) {
      expect(hero.hp, hero.name).toBeGreaterThan(0);
      expect(hero.hp, hero.name).toBeLessThanOrEqual(hero.maxHp);
    }
    // And building it again does not heal anyone (the old Aid did).
    const again = buildCampaignParty(c).map((h) => h.hp);
    expect(buildCampaignParty(c).map((h) => h.hp)).toEqual(again);
  });

  it('fights, reads back, rests, and saves again', () => {
    const c = load();
    readBackSurvivors(c, buildCampaignParty(c));
    expect(hitDiceLeft(c, 0), 'spent hit dice were refilled by the fight').toBe(1);
    longRest(c);
    expect(hitDiceLeft(c, 0)).toBe(hitDiceMax(c));
    expect(c.characters.every((ch) => !ch.resources?.effects?.aid), 'Aid outlived the rest').toBe(true);
    expect(parseCampaign(JSON.stringify(c))).toBeDefined();
  });
});

describe('an arena run saved by the old build', () => {
  const load = () => {
    const raw = JSON.parse(unwrapped('arena-2026-09.json')) as { campaign: unknown; run: ArenaRunState };
    const c = parseCampaign(JSON.stringify(raw.campaign))!;
    expect(c).toBeDefined();
    return { c, run: raw.run };
  };

  it('offers the day\'s doors and can be played on', () => {
    const { c, run } = load();
    const half = run.half ?? 'morning';
    const level = partyLevelOf(c);
    expect(gatesFor(run.seed, level, run.wave, half)).toHaveLength(3);
    // The old lock lived in `attempts`; the old save has no pinned doors, so
    // it opens unlocked rather than stuck on a door it never chose.
    expect(gateLocked(run, half)).toBe(false);
    // A check keyed on the old calendar day simply does not apply any more.
    expect(attemptFor(run.gambit, run.wave, half)).toBeUndefined();

    const wave = buildWave(run.seed, level, run.wave, undefined, run.gate ?? 0, half);
    const foes = wave.encounter.members.map((m, i) => ({ ...buildMonster(m, 'team2', { x: i, y: 9 }), id: `m${i}` }));
    const combat = new Combat({ seed: 1, map: wave.map, combatants: [...buildCampaignParty(c), ...foes] });
    expect(combat.isOver()).toBe(false);

    lunch(c);
    const next = advanceDay(run, true, 0);
    expect(next.half).toBe('afternoon');
    night(c, next.cleared);
    expect(parseCampaign(JSON.stringify(c))).toBeDefined();
  });
});

describe('an adventure saved by the old build', () => {
  it('resumes where it was, and carries on', () => {
    const module = moduleById('hollow-road')!;
    const state = parseAdventure(fixture('adventure-2026-09.json'), module);
    expect(state, 'the save no longer parses').toBeDefined();
    expect(currentScene(state!, module).id).toBe('road-ambush');
    const choice = legalChoices(state!, module).find((c) => !c.blocked);
    if (choice) choose(state!, module, choice.choice.id);
    expect(parseAdventure(serializeAdventure(state!), module)).toBeDefined();
  });
});
