/**
 * Emit a Markdown reference for everything the game actually implements.
 *
 *   npm run reference           # write docs/reference/*.md
 *   npm run reference -- --check  # fail if the files on disk are stale
 *
 * The point is that this is *derived*, never written by hand. Hand-kept content
 * lists rot silently — docs/SPEC.md has claimed a wrong monster count more than
 * once — and the failure is invisible because nothing reads them. Here the data
 * modules are the single source of truth and these files are their printout, so
 * "the docs are wrong" becomes a failing test rather than something a reader
 * discovers.
 *
 * What is emitted is what the engine can see: declared fields, plus the few
 * numbers derived the same way the engine derives them (a monster's XP, its
 * proficiency bonus, a class's slot table). Behaviour that lives inside a
 * `cast` or `apply` closure is deliberately NOT paraphrased — a summary of code
 * is the kind of thing that goes stale without anyone noticing, which is the
 * problem this script exists to solve. Where the effect cannot be read off the
 * data, the row says how it is aimed and leaves the rest to the source.
 */
import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { MONSTERS, MONSTER_XP, monsterLevel, canThreatenAtRange, type MonsterData } from '../src/data/monsters.js';
import { SPELLS, type SpellData, type SpellTargeting } from '../src/data/spells.js';
import { ITEMS } from '../src/data/items.js';
import { WEAPONS } from '../src/data/weapons.js';
import { ARMOR } from '../src/data/armor.js';
import { SPECIES } from '../src/data/species.js';
import { CLASSES, SKILL_LABEL } from '../src/data/classes.js';
import { FEATURES, BREATH_WEAPONS } from '../src/data/features.js';
import { BACKGROUNDS } from '../src/data/backgrounds.js';
import { ENCOUNTERS } from '../src/data/encounters.js';
import { MAPS, parseMap } from '../src/data/maps.js';
import { TRINKETS, trinketSlot } from '../src/data/trinkets.js';
import { VALUABLES } from '../src/data/valuables.js';
import { CONDITION_NAME } from '../src/data/conditions.js';
import { MODULES, playableModules } from '../src/data/modules/index.js';
import { abilityMod, proficiencyBonus } from '../src/engine/types.js';

const OUT = fileURLToPath(new URL('../docs/reference/', import.meta.url));

// --- small formatting helpers ----------------------------------------------

/** A Markdown table cell: em dash for nothing, so columns never collapse. */
function cell(v: unknown): string {
  if (v === undefined || v === null || v === '' || (Array.isArray(v) && v.length === 0)) return '—';
  if (Array.isArray(v)) return v.join(', ');
  if (typeof v === 'boolean') return v ? 'yes' : '—';
  return String(v).replace(/\|/g, '\\|');
}

function table(headers: string[], rows: unknown[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.map(cell).join(' | ')} |`).join('\n');
  return [head, rule, body].join('\n');
}

const byName = <T extends { name: string }>(a: T, b: T): number => a.name.localeCompare(b.name);

function signed(n: number): string {
  return n >= 0 ? `+${n}` : String(n);
}

/** The header every generated file carries, so nobody edits one by hand. */
function preamble(title: string, note: string): string {
  return [
    `# ${title}`,
    '',
    '> Generated by `npm run reference` from the data modules in `src/data/`.',
    '> Do not edit by hand — edit the data and regenerate.',
    '',
    note,
    '',
  ].join('\n');
}

// --- monsters ---------------------------------------------------------------

/** How a monster's stat block reads at the table: "Str 16 (+3)". */
function abilityLine(m: MonsterData): string {
  return (['str', 'dex', 'con', 'int', 'wis', 'cha'] as const)
    .map((a) => `${a.toUpperCase()} ${m.abilities[a]} (${signed(abilityMod(m.abilities[a]))})`)
    .join(', ');
}

function monsterAttacks(m: MonsterData): string {
  return m.weaponIds
    .map((wid) => {
      const w = WEAPONS[wid];
      if (!w) return wid;
      const bits = [`${w.name} ${w.damage} ${w.damageType}`];
      if (w.range) bits.push(`${w.range.normal}/${w.range.long} ft`);
      else if (!w.melee) bits.push('ranged');
      if (w.onHitCondition) bits.push(`on hit: ${w.onHitCondition}`);
      if (w.onHitSave) bits.push(`${w.onHitSave.ability.toUpperCase()} DC ${w.onHitSave.dc} or ${w.onHitSave.condition}`);
      if (w.extraDamage) bits.push(`+${w.extraDamage.dice} ${w.extraDamage.type}`);
      if (w.slays) bits.push(`+${w.slays.dice} vs ${w.slays.types.join('/')}`);
      return bits.join(', ');
    })
    .join('; ');
}

function monstersDoc(): string {
  const all = Object.values(MONSTERS).sort((a, b) => (MONSTER_XP[a.id] ?? 0) - (MONSTER_XP[b.id] ?? 0) || a.name.localeCompare(b.name));
  const casters = all.filter((m) => m.spellcasting);

  const rows = all.map((m) => [
    m.name,
    `\`${m.id}\``,
    m.creatureType,
    MONSTER_XP[m.id] ?? 0,
    m.cr ?? '≤4',
    m.ac,
    m.hp,
    `${m.speed} ft`,
    m.attacksPerAction ?? 1,
    canThreatenAtRange(m.id) ? 'yes' : '—',
    m.minPartyLevel ?? '—',
  ]);

  const detail = all
    .map((m) => {
      const lines: string[] = [`### ${m.name}`, '', `\`${m.id}\` · ${m.creatureType} · ${MONSTER_XP[m.id] ?? 0} XP · AC ${m.ac} · ${m.hp} HP · ${m.speed} ft · PB ${signed(proficiencyBonus(monsterLevel(m.cr)))}`, '', abilityLine(m), ''];
      const add = (label: string, v: unknown) => {
        if (v === undefined || (Array.isArray(v) && v.length === 0)) return;
        lines.push(`- **${label}:** ${cell(v)}`);
      };
      add('Saving throws', m.savingThrowProfs?.map((s) => s.toUpperCase()));
      add('Attacks', monsterAttacks(m));
      add('Features', m.featureIds?.map((f) => FEATURES[f]?.name ?? f));
      add('Resistances', m.resistances);
      add('Resists nonmagical', m.resistNonmagical);
      add('Immunities', m.immunities);
      add('Vulnerabilities', m.vulnerabilities);
      if (m.regeneration) add('Regeneration', `${m.regeneration.amount}/turn, stopped by ${m.regeneration.stoppedBy.join('/')}`);
      if (m.holdDamage) add('Hold damage', `${m.holdDamage.dice} ${m.holdDamage.type} to whoever it has restrained`);
      if (m.deathBurst) add('Death burst', `${m.deathBurst.dice} ${m.deathBurst.type}, ${m.deathBurst.save.ability.toUpperCase()} DC ${m.deathBurst.save.dc}, ${m.deathBurst.radius} ft`);
      if (m.spellcasting) {
        const slots = m.spellcasting.slots.map((n, i) => `${n}×L${i + 1}`).join(' ');
        add('Spellcasting', `${m.spellcasting.ability.toUpperCase()}, slots ${slots || 'none'}`);
        add('Spells', m.spellcasting.spellIds.map((s) => SPELLS[s]?.name ?? s));
      }
      if (m.minPartyLevel) add('Held back until party level', m.minPartyLevel);
      if (m.metalArmor) add('Metal armor', 'yes (Shocking Grasp rider)');
      lines.push('');
      return lines.join('\n');
    })
    .join('\n');

  return [
    preamble('Monsters', `${all.length} monsters, ${casters.length} of them spellcasters. Sorted by XP.`),
    '## At a glance',
    '',
    table(
      ['Name', 'ID', 'Type', 'XP', 'CR', 'AC', 'HP', 'Speed', 'Attacks', 'Ranged?', 'Min party lvl'],
      rows,
    ),
    '',
    '## Stat blocks',
    '',
    detail,
  ].join('\n');
}

// --- spells -----------------------------------------------------------------

/** How a spell is aimed, in words — derived from `targeting`, never hand-kept. */
function aiming(t: SpellTargeting): string {
  switch (t.kind) {
    case 'creature': {
      const who = t.who === 'any' ? 'creature' : t.who;
      const n = t.count > 1 ? `${t.count} ${who}s` : `1 ${who}`;
      const types = t.creatureType ? ` (${t.creatureType} only)` : t.creatureTypes ? ` (${t.creatureTypes.join('/')} only)` : '';
      // Range 0 is a touch spell, and "within 0 ft" reads as a bug.
      const reach = t.range === 0 ? 'you can touch' : `within ${t.range} ft`;
      return `${n} ${reach}${types}`;
    }
    case 'weaponAttack': return 'the weapon in hand (its own reach)';
    case 'sphere2x2': return `2×2 burst within ${t.range} ft`;
    case 'sphere5x5': return `5×5 burst within ${t.range} ft`;
    case 'cone15': return '15 ft cone';
    case 'cube15': return '15 ft cube (adjacent)';
    case 'line15': return 'line to the board edge';
    case 'emptyCell': return `an empty cell within ${t.range} ft`;
    case 'self': return t.anyTime ? 'self (castable any time)' : 'self (offered when it would reach someone)';
  }
}

/** Every class list a spell appears on, and the level it arrives. */
function spellSources(): Map<string, string[]> {
  const out = new Map<string, string[]>();
  const push = (id: string, src: string) => {
    const list = out.get(id) ?? [];
    if (!list.includes(src)) list.push(src);
    out.set(id, list);
  };
  for (const c of Object.values(CLASSES)) {
    for (const [lvl, ids] of Object.entries(c.spellcasting?.spellsByLevel ?? {})) {
      for (const id of ids) push(id, `${c.name} ${lvl}`);
    }
    for (const id of c.spellcasting?.learnableExtra ?? []) push(id, `${c.name} (scroll)`);
  }
  for (const s of Object.values(SPECIES)) {
    for (const ids of Object.values(s.spellsByLevel ?? {})) for (const id of ids) push(id, s.name);
    for (const inn of s.innateSpells ?? []) push(inn.spellId, s.name);
  }
  for (const m of Object.values(MONSTERS)) {
    for (const id of m.spellcasting?.spellIds ?? []) push(id, m.name);
  }
  return out;
}

function spellsDoc(): string {
  const all = Object.values(SPELLS).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name));
  const sources = spellSources();
  const counts = new Map<number, number>();
  for (const s of all) counts.set(s.level, (counts.get(s.level) ?? 0) + 1);
  const tally = [...counts].sort((a, b) => a[0] - b[0])
    .map(([lvl, n]) => `${lvl === 0 ? 'cantrips' : `level ${lvl}`}: ${n}`).join(', ');

  const sections = [...counts.keys()].sort((a, b) => a - b).map((lvl) => {
    const at = all.filter((s) => s.level === lvl);
    const rows = at.map((s: SpellData) => [
      `${s.icon} ${s.name}`,
      `\`${s.id}\``,
      s.castingTime,
      aiming(s.targeting),
      s.concentration ? 'yes' : '—',
      s.upcast ? 'yes' : '—',
      [s.ritual ? 'ritual' : '', s.outOfCombat ? 'out of combat' : ''].filter(Boolean).join(', ') || '—',
      (sources.get(s.id) ?? []).join(', ') || '—',
    ]);
    return [
      `## ${lvl === 0 ? 'Cantrips' : `Level ${lvl}`}`,
      '',
      table(['Spell', 'ID', 'Cast', 'Aimed at', 'Conc.', 'Upcast', 'Notes', 'Known by'], rows),
      '',
    ].join('\n');
  });

  return [
    preamble('Spells', [
      `${all.length} spells — ${tally}.`,
      '',
      '**Upcast** marks a spell `legalActions` offers at every slot the caster can',
      'afford, because its effect scales. Anything unmarked is offered at its own',
      'level only, and spending a bigger slot on it would buy nothing.',
      '',
      '**Aimed at** is derived from the spell\'s `targeting`, so it is always true.',
      'What the spell *does* lives in its `cast` closure and is not paraphrased here —',
      'see `src/data/spells.ts`.',
    ].join('\n')),
    ...sections,
  ].join('\n');
}

// --- gear -------------------------------------------------------------------

function gearDoc(): string {
  const weapons = Object.values(WEAPONS).sort(byName);
  const armor = Object.values(ARMOR).sort(byName);
  const items = Object.values(ITEMS).sort(byName);
  const trinkets = Object.values(TRINKETS).sort(byName);
  const valuables = Object.values(VALUABLES).sort(byName);

  const itemTarget = (t: (typeof items)[number]['targeting']): string => {
    switch (t.kind) {
      case 'self': return 'self';
      case 'ally': return 'self or adjacent ally';
      case 'thrown': return `thrown, ${t.range.normal}/${t.range.long} ft`;
      case 'spell': return `casts ${SPELLS[t.spellId]?.name ?? t.spellId}`;
    }
  };

  return [
    preamble('Gear', `${weapons.length} weapons, ${armor.length} armors, ${items.length} consumables, ${trinkets.length} trinkets, ${valuables.length} valuables.`),
    '## Weapons',
    '',
    table(
      ['Name', 'ID', 'Damage', 'Type', 'Range', 'Melee', 'Mastery', 'Properties', 'Riders'],
      weapons.map((w) => [
        w.name, `\`${w.id}\``, w.damage, w.damageType,
        w.range ? `${w.range.normal}/${w.range.long} ft` : '—',
        w.melee, w.mastery, w.properties,
        [
          w.bonusDiceOnAdvantage ? `+${w.bonusDiceOnAdvantage} with advantage` : '',
          w.onHitCondition ? `on hit: ${w.onHitCondition}` : '',
          w.onHitSave ? `${w.onHitSave.ability.toUpperCase()} DC ${w.onHitSave.dc} or ${w.onHitSave.condition}` : '',
          w.extraDamage ? `+${w.extraDamage.dice} ${w.extraDamage.type}${w.extraDamage.save ? ` (${w.extraDamage.save.ability.toUpperCase()} DC ${w.extraDamage.save.dc} halves)` : ''}` : '',
          w.slays ? `+${w.slays.dice} ${w.slays.damageType ?? w.damageType} vs ${w.slays.types.join('/')}` : '',
          w.lifeSteal ? `crit: +${w.lifeSteal.amount} necrotic, drained (not ${w.lifeSteal.exempt.join('/')})` : '',
          ...(w.grants?.featureIds ?? []).map((f) => FEATURES[f]?.name ?? f),
          w.grants?.hpPerLevel ? `+${w.grants.hpPerLevel} max HP per level` : '',
          w.attackBonus || w.damageBonus ? `+${w.attackBonus ?? 0}/+${w.damageBonus ?? 0}` : '',
        ].filter(Boolean).join('; '),
      ]),
    ),
    '',
    '## Armor',
    '',
    table(
      ['Name', 'ID', 'Base AC', 'Dex cap', 'Category', 'Str', 'Stealth', 'Metal', 'Cost (gp)', 'Rarity', 'Notes'],
      armor.map((a) => [
        a.name, `\`${a.id}\``, a.base, a.dexCap, a.category,
        a.strMin ?? '', a.stealthDisadvantage ? 'disadvantage' : '',
        a.metal, a.cost, a.rarity, a.noCrit ? 'crits become normal hits' : '',
      ]),
    ),
    '',
    '## Consumables',
    '',
    table(
      ['Name', 'ID', 'Use', 'Targeting', 'Cost (gp)', 'Rarity'],
      items.map((i) => [i.name, `\`${i.id}\``, i.useTime, itemTarget(i.targeting), i.cost, i.rarity]),
    ),
    '',
    '## Trinkets',
    '',
    table(
      ['Name', 'ID', 'Slot', 'Cost (gp)', 'Rarity', 'Grants', 'Blurb'],
      trinkets.map((t) => [
        t.name, `\`${t.id}\``, trinketSlot(t), t.cost, t.rarity,
        [
          ...(t.grants.featureIds ?? []).map((f) => FEATURES[f]?.name ?? f),
          ...(t.grants.resistances ?? []).map((r) => `resist ${r}`),
          ...Object.entries(t.grants.abilityFloor ?? {}).map(([a, v]) => `${a.toUpperCase()} at least ${v}`),
        ].join(', '),
        t.blurb,
      ]),
    ),
    '',
    '## Valuables',
    '',
    'Loot with no mechanical effect — sold for gold.',
    '',
    table(['Name', 'ID', 'Cost (gp)', 'Rarity'], valuables.map((v) => [v.name, `\`${v.id}\``, v.cost, v.rarity])),
    '',
  ].join('\n');
}

// --- characters -------------------------------------------------------------

function classesDoc(): string {
  const all = Object.values(CLASSES).sort(byName);
  const maxLevel = Math.max(...all.map((c) => Math.max(...Object.keys(c.featuresByLevel).map(Number))));

  const sections = all.map((c) => {
    const lines = [
      `## ${c.name}`,
      '',
      `\`${c.id}\` · d${c.hitDie} hit die · saves ${c.savingThrows.map((s) => s.toUpperCase()).join(' & ')}`,
      '',
      `- **Armor:** ${cell(c.armorProfs)}`,
      `- **Skills offered:** ${c.skillProfs.map((s) => SKILL_LABEL[s]).join(', ')}`,
      `- **Ability priority:** ${c.statPriority.map((a) => a.toUpperCase()).join(' > ')}`,
      `- **Weapon masteries:** ${cell(c.weaponMasteries.map((w) => WEAPONS[w]?.name ?? w))}`,
      `- **Starting kit:** ${[
        WEAPONS[c.equipment.mainHand]?.name ?? c.equipment.mainHand,
        c.equipment.offHand === 'shield' ? 'shield' : c.equipment.offHand ? WEAPONS[c.equipment.offHand]?.name ?? c.equipment.offHand : '',
        c.equipment.armor ? ARMOR[c.equipment.armor]?.name ?? c.equipment.armor : '',
        // A starting pack holds spare weapons as well as potions, so the id
        // has to be looked up in both tables.
        ...c.equipment.inventory.map((s) => `${ITEMS[s.itemId]?.name ?? WEAPONS[s.itemId]?.name ?? s.itemId} ×${s.qty}`),
      ].filter(Boolean).join(', ')}`,
      '',
      '### Features by level',
      '',
      table(['Level', 'Features'], Object.entries(c.featuresByLevel)
        .sort((a, b) => Number(a[0]) - Number(b[0]))
        .map(([lvl, ids]) => [lvl, ids.map((f) => FEATURES[f]?.name ?? f).join(', ')])),
      '',
    ];

    if (c.spellcasting) {
      const sc = c.spellcasting;
      lines.push('### Spell slots', '');
      const widest = Math.max(...sc.slotsByLevel.map((r) => r.length));
      lines.push(table(
        ['Level', ...Array.from({ length: widest }, (_, i) => `${i + 1}${['st', 'nd', 'rd', 'th'][Math.min(i, 3)]}`),
          ...(sc.cantripsKnownByLevel ? ['Cantrips'] : []),
          ...(sc.spellbookByLevel ? ['Spellbook'] : []),
          ...(sc.preparedByLevel ? ['Prepared'] : [])],
        sc.slotsByLevel.map((row, i) => [
          i + 1,
          ...Array.from({ length: widest }, (_, j) => row[j] ?? '—'),
          ...(sc.cantripsKnownByLevel ? [sc.cantripsKnownByLevel[i] ?? '—'] : []),
          ...(sc.spellbookByLevel ? [sc.spellbookByLevel[i] ?? '—'] : []),
          ...(sc.preparedByLevel ? [sc.preparedByLevel[i] ?? '—'] : []),
        ]),
      ), '');
      lines.push(`Spellcasting ability: **${sc.ability.toUpperCase()}**.`, '');
      lines.push('### Spell list', '',
        // Keyed by CHARACTER level — the level at which the spells arrive —
        // not by spell level. Labelling it "Level" invites exactly the wrong
        // reading, since every other slot table on the page means spell level.
        table(['Arrives at character level', 'Spells (in priority order — the auto-loadout takes the first few)'],
          Object.entries(sc.spellsByLevel).sort((a, b) => Number(a[0]) - Number(b[0]))
            .map(([lvl, ids]) => [lvl, ids.map((s) => SPELLS[s]?.name ?? s).join(', ')])), '');
      if (sc.learnableExtra?.length) {
        lines.push(`Learnable from scrolls found in play: ${sc.learnableExtra.map((s) => SPELLS[s]?.name ?? s).join(', ')}.`, '');
      }
    }

    for (const cp of c.choices ?? []) {
      lines.push(`### Choice: ${cp.label} (level ${cp.atLevel})`, '',
        table(['Option', 'Grants', 'Blurb'], cp.options.map((o) => [
          o.id === cp.default ? `${o.name} *(default)*` : o.name,
          [
            ...(o.grants.featureIds ?? []).map((f) => FEATURES[f]?.name ?? f),
            ...(o.grants.spellIds ?? []).map((s) => SPELLS[s]?.name ?? s),
            ...(o.grants.weaponMasteries ?? []).map((w) => `mastery: ${WEAPONS[w]?.name ?? w}`),
            ...(o.grants.resistances ?? []).map((r) => `resist ${r}`),
          ].join(', '),
          o.blurb,
        ])), '');
    }
    return lines.join('\n');
  });

  return [
    preamble('Classes', `${all.length} playable classes, levels 1–${maxLevel}.`),
    ...sections,
  ].join('\n');
}

function charactersDoc(): string {
  const species = Object.values(SPECIES).sort(byName);
  const backgrounds = Object.values(BACKGROUNDS).sort(byName);
  return [
    preamble('Species & Backgrounds', `${species.length} species, ${backgrounds.length} backgrounds.`),
    '## Species',
    '',
    table(
      ['Name', 'ID', 'Speed', 'HP/level', 'Resistances', 'Features', 'Cantrips', 'Innate spells'],
      species.map((s) => [
        s.name, `\`${s.id}\``, `${s.speed} ft`, s.hpPerLevel, s.resistances,
        s.featureIds?.map((f) => FEATURES[f]?.name ?? f),
        Object.entries(s.spellsByLevel ?? {}).map(([lvl, ids]) => `${ids.map((i) => SPELLS[i]?.name ?? i).join('/')} (from char. level ${lvl})`),
        s.innateSpells?.map((i) => `${SPELLS[i.spellId]?.name ?? i.spellId} ×${i.uses}/encounter (from char. level ${i.atLevel})`),
      ]),
    ),
    '',
    '## Backgrounds',
    '',
    table(
      ['Name', 'ID', 'Skills', 'Tool', 'Blurb'],
      backgrounds.map((b) => [b.name, `\`${b.id}\``, b.skills.map((s) => SKILL_LABEL[s]).join(', '), b.toolNote, b.blurb]),
    ),
    '',
  ].join('\n');
}

function featuresDoc(): string {
  const all = Object.values(FEATURES).sort(byName);
  const usesOf = (f: (typeof all)[number]): string => {
    // "Recharge 5–6" and "Recharge 6" — a range of one is written as one.
    if (f.recharge) return f.recharge >= 6 ? 'recharge 6' : `recharge ${f.recharge}–6`;
    if (!f.uses) return '—';
    // The clock in prose, not in the enum's spelling: this table is read by a
    // person deciding whether a feature is a per-fight trick or the day's
    // budget, and `1/shortRest` makes them stop and parse an identifier.
    const clock = { encounter: 'fight', shortRest: 'short rest', longRest: 'long rest' }[f.uses.per];
    return `${f.uses.count}/${clock}`;
  };
  return [
    preamble('Features', [
      `${all.length} features — class abilities, species traits, monster traits and trinket grants,`,
      'all in one namespace because the engine resolves them the same way.',
      '',
      '`Trigger` is how it is taken: an action, a bonus action, `free` (rider on',
      'something else) or `passive` (always on).',
    ].join('\n')),
    table(
      ['Name', 'ID', 'Trigger', 'Uses', 'Adv. dice', 'Notes'],
      all.map((f) => [
        f.name, `\`${f.id}\``, f.trigger, usesOf(f),
        f.advantageDice ? f.advantageDice(5) + ' (at level 5)' : '—',
        [
          f.manualUses ? 'spends its own pool' : '',
          BREATH_WEAPONS[f.id]
          ? (() => {
              const b = BREATH_WEAPONS[f.id]!;
              const shape = b.shape === 'line' ? `${(b.length ?? 0) * 5} ft line` : '15 ft cone';
              return `${shape}, ${b.dice} ${b.damageType}, ${b.save.toUpperCase()} save`;
            })()
          : '',
          !f.apply ? 'read by the rules, no action of its own' : '',
        ].filter(Boolean).join('; '),
      ]),
    ),
    '',
    '## Conditions',
    '',
    'What the engine can put on a combatant, and what the log calls it.',
    '',
    table(['ID', 'Log name'], Object.entries(CONDITION_NAME).sort().map(([id, name]) => [`\`${id}\``, name])),
    '',
  ].join('\n');
}

// --- content ----------------------------------------------------------------

function contentDoc(): string {
  const encounters = Object.values(ENCOUNTERS).sort((a, b) => a.suggestedLevel - b.suggestedLevel || a.name.localeCompare(b.name));
  const maps = Object.values(MAPS).sort(byName);
  const modules = [...MODULES].sort((a, b) => a.title.localeCompare(b.title));
  // Two of the five are test scaffolding kept out of the player's menu; the
  // reference lists them, but says which is which.
  const shipped = new Set(playableModules(false).map((m) => m.id));

  const encounterXp = (m: string[]): number => m.reduce((s, id) => s + (MONSTER_XP[id] ?? 0), 0);
  const roster = (m: string[]): string => {
    const counts = new Map<string, number>();
    for (const id of m) counts.set(id, (counts.get(id) ?? 0) + 1);
    return [...counts].map(([id, n]) => `${n}× ${MONSTERS[id]?.name ?? id}`).join(', ');
  };

  return [
    preamble('Encounters, Maps & Modules', `${encounters.length} hand-built encounters, ${maps.length} maps, ${modules.length} adventure modules.`),
    '## Encounters',
    '',
    'Hand-built fights. The arena generates its own from an XP budget instead — see `src/arena/encounter.ts`.',
    '',
    table(
      ['Name', 'ID', 'Suggested level', 'Total XP', 'Roster'],
      encounters.map((e) => [e.name, `\`${e.id}\``, e.suggestedLevel, encounterXp(e.members), roster(e.members)]),
    ),
    '',
    '## Maps',
    '',
    table(
      ['Name', 'ID', 'Theme', 'Size', 'Walls', 'Difficult', 'Hazard'],
      maps.map((m) => {
        const grid = parseMap(m);
        const count = (t: string) => grid.cells.filter((c) => c.terrain === t).length;
        return [m.name, `\`${m.id}\``, m.theme, `${grid.width}×${grid.height}`, count('wall'), count('difficult'), count('hazard')];
      }),
    ),
    '',
    '## Adventure modules',
    '',
    table(
      ['Title', 'ID', 'Levels', 'Scenes', 'Sequel', 'Shown in the menu', 'Blurb'],
      modules.map((m) => [
        m.title,
        `\`${m.id}\``,
        m.levelBand ? `${m.levelBand.from}–${m.levelBand.to}` : '—',
        Object.keys(m.scenes).length,
        m.sequel ?? '—',
        shipped.has(m.id) ? 'yes' : 'dev only',
        m.blurb,
      ]),
    ),
    '',
  ].join('\n');
}

// --- index ------------------------------------------------------------------

function indexDoc(files: Array<{ file: string; title: string; summary: string }>): string {
  const spellCount = Object.keys(SPELLS).length;
  const maxLevel = Math.max(...Object.values(CLASSES).flatMap((c) => Object.keys(c.featuresByLevel).map(Number)));
  return [
    preamble('Content Reference', [
      'Everything the game implements, printed from the data modules.',
      '',
      `**${Object.keys(MONSTERS).length}** monsters · **${spellCount}** spells ·`,
      `**${Object.keys(CLASSES).length}** classes (levels 1–${maxLevel}) ·`,
      `**${Object.keys(SPECIES).length}** species · **${Object.keys(FEATURES).length}** features ·`,
      `**${Object.keys(WEAPONS).length}** weapons · **${Object.keys(ITEMS).length}** consumables ·`,
      `**${Object.keys(ENCOUNTERS).length}** encounters · **${Object.keys(MAPS).length}** maps`,
    ].join('\n')),
    table(['File', 'Contents'], files.map((f) => [`[${f.title}](./${f.file})`, f.summary])),
    '',
    '## Regenerating',
    '',
    '```sh',
    'npm run reference            # rewrite these files',
    'npm run reference -- --check # fail if they are stale (CI does this)',
    '```',
    '',
  ].join('\n');
}

// --- driver -----------------------------------------------------------------

const FILES: Array<{ file: string; title: string; summary: string; build: () => string }> = [
  { file: 'monsters.md', title: 'Monsters', summary: 'Every stat block: abilities, attacks, features, spell kits, XP.', build: monstersDoc },
  { file: 'spells.md', title: 'Spells', summary: 'Every spell by level, how it is aimed, whether it upcasts, and who knows it.', build: spellsDoc },
  { file: 'gear.md', title: 'Gear', summary: 'Weapons, armor, consumables, trinkets and valuables.', build: gearDoc },
  { file: 'classes.md', title: 'Classes', summary: 'Per class: proficiencies, features by level, slot table, spell list, choices.', build: classesDoc },
  { file: 'characters.md', title: 'Species & Backgrounds', summary: 'Species traits and innate magic; background skills.', build: charactersDoc },
  { file: 'features.md', title: 'Features & Conditions', summary: 'Every named feature and every condition the engine can apply.', build: featuresDoc },
  { file: 'content.md', title: 'Encounters, Maps & Modules', summary: 'Hand-built fights, map terrain counts, adventure modules.', build: contentDoc },
];

function render(): Map<string, string> {
  const out = new Map<string, string>();
  for (const f of FILES) out.set(f.file, f.build().trimEnd() + '\n');
  out.set('README.md', indexDoc(FILES).trimEnd() + '\n');
  return out;
}

const check = process.argv.includes('--check');
const rendered = render();

if (check) {
  const stale: string[] = [];
  for (const [file, body] of rendered) {
    const path = join(OUT, file);
    if (!existsSync(path) || readFileSync(path, 'utf8') !== body) stale.push(file);
  }
  if (stale.length > 0) {
    console.error(`Reference docs are stale: ${stale.join(', ')}`);
    console.error('Run `npm run reference` and commit the result.');
    process.exit(1);
  }
  console.log(`Reference docs are up to date (${rendered.size} files).`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [file, body] of rendered) {
    const path = join(OUT, file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`${path}  (${body.split('\n').length} lines)`);
  }
}
